# Generated by Django 3.1.6 on 2021-03-02 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trello', '0003_auto_20210301_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 9, 12, 3, 390983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 9, 12, 3, 349983, tzinfo=utc)),
        ),
    ]
